name: staff_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  qr_code_scanner: ^0.6.1
  charts_flutter: ^0.11.0
  uuid: ^2.2.2
  firebase_core: ^1.10.6
  octo_image: ^1.0.1
  expandable: ^5.0.1
  meta: ^1.7.0
  built_collection: ^4.3.2
  loading_indicator: ^3.0.2
  google_sign_in: ^4.5.9
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.6.5+3
  firebase_storage: ^0.3.2
  flutter_dotenv: ^5.0.2
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  tuple: ^1.0.3
  rxdart: ^0.27.0
  http: ^0.12.2
  firebase_auth: ^0.6.2+1
  built_value: ^7.1.0
  rx_redux: ^2.1.1
  distinct_value_connectable_stream: ^1.1.1
  flutter_provider: ^2.1.0
  rx_shared_preferences: ^2.1.0
  disposebag: ^1.5.0
  flutter_disposebag: ^1.1.0
  flutter_bloc_pattern: ^2.1.1
  rxdart_ext: ^0.1.3
  cached_network_image: ^2.0.0
  listenable_stream: ^1.1.0
  stream_loader: ^1.4.0

dev_dependencies:
  built_value_generator: ^7.1.1
  build_runner: ^1.11.1+1
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

#dependency_overrides:
#analyzer: ^0.41.1
#path_provider: 2.0.0-nullsafety.1
#shared_preferences:
#git:
#url: https://github.com/Flutter-Dart-Open-Source/plugins.git
#path: packages/shared_preferences/shared_preferences
#ref: 051e38e939272c6c60546c4689d9a15e01df17ad
#rxdart: ^0.26.0
#intl: ^0.17.0
#meta: ^1.3.0
#clock: ^1.1.0
#path: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Thin.ttf
        weight: 100
      - asset: assets/fonts/Montserrat-ThinItalic.ttf
        weight: 100
        style: italic

      - asset: assets/fonts/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        weight: 200
        style: italic

      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-LightItalic.ttf
        weight: 300
        style: italic

      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Italic.ttf
        weight: 400
        style: italic

      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-MediumItalic.ttf
        weight: 500
        style: italic

      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        weight: 600
        style: italic

      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-BoldItalic.ttf
        weight: 700
        style: italic

      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        weight: 800
        style: italic

      - asset: assets/fonts/Montserrat-Black.ttf
        weight: 900
      - asset: assets/fonts/Montserrat-BlackItalic.ttf
        weight: 900
        style: italic